name: Set up WireGuard Connection

permissions:
  actions: write
  contents: read

env:
  WEBHOOK_ENDPOINT: ${{ secrets.WEBHOOK_ENDPOINT }}

on:
  push:
    branches:
        - main
    tags:
        - 'v**'

    paths:
        - '.github/workflows/easy-action.yml'

  workflow_dispatch:

jobs:
  wireguard:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      
    - name: Get WireGuard Configuration
      id: config
      shell: bash
      run: |
        if [ -z "${{ inputs.WG_CONFIG }}" ]; then
            echo "WG_CONFIG не задан, используется значение по умолчанию: env.DEFAULT_CONFIG"
        else
            echo "CONFIG=${{ inputs.WG_CONFIG }}" >> $GITHUB_ENV
        fi

    - name: Get Endpoint Address
      shell: bash
      run: |
        sudo apt update -y
        sudo apt install -y net-tools
        sudo apt install -y iptables
        sudo apt install -y iproute2
        curl -A "Endpoint = " ${{ env.WEBHOOK_ENDPOINT }}?iface=wg0

      continue-on-error: true

    - name: Set up WireGuard Connection
      uses: vados-dev/wg-connect-action@v1
      with:
        WG_CONFIG: ${{ secrets.WIREGUARD_CONFIG }}

    - name: Attach WireGuard connection
      shell: bash
      run: |
        sudo wg show
        sudo wg showconf wg0
        sudo ifconfig
        sudo netstat -tulpn | grep 29185
        sudo iptables -L -v -n
        sudo iptables -t nat -L -v -n
        sudo iptables -t nat -L -v -n --line-numbers
        sudo ip address
        sudo ip link
        sudo ip r
        curl -A "endpoint = " ${{ env.WEBHOOK_ENDPOINT }}?type=with-vpn-1
        ping ya.ru
        
    - name: Detach WireGuard connection
      if: ${{ failure() }}
      shell: bash
      run: |
        sudo wg-quick down /etc/wireguard/wg0.conf
