name: Set up WireGuard Connection

permissions:
  actions: write
  contents: read

env:
  WEBHOOK_ENDPOINT: ${{ secrets.WEBHOOK_ENDPOINT }}

on:
  push:
    branches:
        - main
    tags:
        - 'v**'

    paths:
        - '.github/workflows/easy-action.yml'

  workflow_dispatch:

jobs:
  wireguard:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      
    - name: Get WireGuard Configuration
      id: config
      shell: bash
      run: |
        if [ -z "${{ inputs.WG_CONFIG }}" ]; then
            echo "WG_CONFIG не задан, используется значение по умолчанию: env.DEFAULT_CONFIG"
        else
            echo "CONFIG=${{ inputs.WG_CONFIG }}" >> $GITHUB_ENV
        fi

    - name: Get Endpoint Address
      shell: bash
      run: |
        sudo apt update -y
        sudo apt install -y net-tools
        sudo apt install -y iptables
        sudo apt install -y iproute2
        sudo apt install -y resolvconf
        curl -A "Endpoint = " ${{ env.WEBHOOK_ENDPOINT }}?iface

      continue-on-error: true

    - name: Set up WireGuard Connection
      uses: egor-tensin/setup-wireguard@v1
      with:
        endpoint: 146.120.64.211:29185
        endpoint_public_key: F0P1v/1/dwGJlDVD1tVlyIAUUd9c5sHokhv/kl5tm1U=
        ips: 10.8.0.1/24
        allowed_ips: 0.0.0.0/0
        private_key: eKhaXEPOR/8uH+6NZz4IsYGV8JIrnm37ZfG7wGEsRWY=
        preshared_key: ngbjGRcY2A25xqy89qaqZ2JBhdDpnJVttcMwnErdjnY=
        keepalive: 15

        #      uses: vados-dev/wg-connect-action@v1
#      with:
#        WG_CONFIG: ${{ secrets.WIREGUARD_CONFIG }}

    - name: Attach WireGuard connection
      shell: bash
      run: |
        sudo wg show
        #sudo wg showconf wg0
        sudo ifconfig
        #sudo netstat -tulpn | grep 29185
        #sudo iptables -L -v -n
        #sudo iptables -t nat -L -v -n
        #sudo iptables -t nat -L -v -n --line-numbers
        #sudo ip address
        #sudo ip link
        #sudo ip r
        curl -A "endpoint = " ${{ env.WEBHOOK_ENDPOINT }}
        
    - name: Detach WireGuard connection
      if: ${{ failure() }}
      shell: bash
      run: |
        sudo wg-quick down /etc/wireguard/wg0.conf
