name: Test VPN

permissions:
  actions: write
  contents: read

env:
    TIME: $(date +'%d.%m.%Y-%T')
    LogFilename: "runner.log"
    WEBHOOK_ENDPOINT: ${{ secrets.WEBHOOK_ENDPOINT }}
    WIREGUARD_CONFIG: ${{ secrets.WIREGUARD_CONFIG }}
    
on:
  push:
  
    paths:
      - '.github/workflows/vpn-access.yml'

  #pull_request:
  workflow_dispatch:

branding:
  icon: shield
  color: red

jobs:
 test-vpn:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Get Endpoint Address
      shell: bash
      run: |
        sudo mkdir ${{ runner.temp }}/logs
        echo "LogDir=${{ runner.temp }}/logs" >> $GITHUB_ENV
        echo "LogFile=${{ env.LOG_DIR }}/${{ env.LogFilename }}" >> $GITHUB_ENV
        curl -A "Endpoint = " ${{ env.WEBHOOK_ENDPOINT }}?iface=wg0 
      continue-on-error: true
        
    - name: Attach WireGuard connection
      shell: bash
      run: |
        sudo apt install -y resolvconf wireguard
        sudo sysctl -w net.ipv4.ip_forward=1
        sudo sysctl -w net.ipv4.conf.all.src_valid_mark=1
        sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
        sudo sysctl -w net.ipv6.conf.all.forwarding=1
        sudo sysctl -w net.ipv6.conf.default.forwarding=1
        echo "net.ipv4.ip_forward=1" | sudo tee /etc/sysctl.conf
        echo "net.ipv4.conf.all.src_valid_mark=1" | sudo tee /etc/sysctl.conf
        echo "ipv6.conf.all.disable_ipv6=1" | sudo tee /etc/sysctl.conf
        echo "net.ipv6.conf.all.forwarding=1" | sudo tee /etc/sysctl.conf
        echo "net.ipv6.conf.default.forwarding=1" | sudo tee /etc/sysctl.conf
        sudo sysctl -p /etc/sysctl.conf
        sudo systemctl enable --now resolvconf
        sudo systemctl start resolvconf
        sudo mkdir /etc/wireguard
        echo "${{ env.WIREGUARD_CONFIG }}" > /etc/wireguard/wg0.conf
        sudo cat /etc/wireguard/wg0.conf
        sudo chmod 600 /etc/wireguard/wg0.conf
        sudo wg-quick up /etc/wireguard/wg0.conf
        sleep 5
        sudo wg show
        sudo wg showconf wg0
        curl -A "endpoint = " ${{ env.WEBHOOK_ENDPOINT }}?type=with-vpn-1
        ping ya.ru
          
    - name: Detach WireGuard connection
      if: ${{ failure() }}
      shell: bash
      run: |
        echo "${{ env.TIME }} - Failure" >> ${{ env.LogFile }}
        sudo wg-quick down /etc/wireguard/wg0.conf >> ${{ env.LogFile }}
        echo "${{ env.TIME }} - Logs from VPN End." >> ${{ env.LogFile }}

    - name: Upload Logs on Failure
      uses: actions/upload-artifact@v4
      with:
        name: Build failure logs
        path: ${{ env.LogDir }}

#branding:
#  icon: shield
#  color: red
