name: Test VPN

on:
  #pull_request:
  workflow_dispatch:

jobs:
 test-vpn:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Get Endpoint Address
      run: |
        set -euo pipefail
        echo "DateTime=$(date +%d.%m.%Y-%T)" >> "$GITHUB_ENV"
        echo "LogDir=${{ runner.temp }}/vpn_logs" >> "$GITHUB_ENV"
        echo "LogFile=${{ env.LogDir }}/runner.log" >> "$GITHUB_ENV"
        sudo mkdir ${{ env.LogDir }} 2>/dev/null > ${{ env.LogFile }}
        echo "${{ env.DateTime }} - Logile Start." >> ${{ env.LogFile }}
        curl -A "Endpoint = " ${{ secrets.WEBHOOK_ENDPOINT }}?iface=wg0 
        continue-on-error: true
        
    - name: Attach WireGuard connection
      shell: bash
      run: |
        sudo apt install -y resolvconf wireguard wireguard-tools
        echo "${{ secrets.WIREGUARD_CONFIG }}" > /etc/wireguard/wg0.conf
        sudo chmod 600 /etc/wireguard/wg0.conf
        sudo wg-quick up /etc/wireguard/wg0.conf
        sleep 5
        sudo wg show
        sudo wg showconf wg0
        curl -A "endpoint = " ${{ secrets.WEBHOOK_ENDPOINT }}?type=with-vpn-1
        ping ya.ru
          
    - name: Detach WireGuard connection
      if: ${{ failure() }}
      shell: bash
      run: |
        echo "${{ env.DateTime }} - Failure - ${0}" >> ${{ env.LogFile }}
        sudo wg-quick down /etc/wireguard/wg0.conf >> ${{ env.LogFile }}
        echo "${{ env.DateTime }} - Logs from VPN End." >> ${{ env.LogFile }}

    - name: Upload Logs on Failure
      uses: actions/upload-artifact@v4
      with:
        name: Build failure logs
        path: ${{ env.LogDir }}

