name: Test VPN

permissions:
  actions: write
  contents: read

env:
  LOG_FILENAME: runner.log

on:
  #pull_request:
  workflow_dispatch:

jobs:
 test-vpn:
    runs-on: ubuntu-latest
    steps:
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Checkout code
      uses: actions/checkout@v7

    - name: Get env variables
      shell: bash
      run: |
        echo "DateTime=$(date +%d.%m.%Y-%T)" >> $GITHUB_ENV
        echo "LogDir=${{ runner.temp }}/logs" >> $GITHUB_ENV
        echo "LogFile="${{ runner.temp }}/logs/${{ env.LOG_FILENAME }}" >> $GITHUB_ENV
      continue-on-error: true

    - name: Get Endpoint Address
      shell: bash
      run: |
        sudo mkdir ${{ env.LogDir }}
        echo "${{ env.DateTime }} - Logile Start." >> ${{ env.LogFile }}
        curl -A "Endpoint = " ${{ secrets.WEBHOOK_ENDPOINT }}?iface=wg0 
      continue-on-error: true
        
    - name: Attach WireGuard connection
      shell: bash
      run: |
        sudo apt install -y resolvconf wireguard wireguard-tools
        echo "${{ secrets.WIREGUARD_CONFIG }}" > /etc/wireguard/wg0.conf
        sudo cat /etc/wireguard/wg0.conf
        sudo chmod 600 /etc/wireguard/wg0.conf
        sudo wg-quick up /etc/wireguard/wg0.conf
        sleep 5
        sudo wg show
        sudo wg showconf wg0
        curl -A "endpoint = " ${{ secrets.WEBHOOK_ENDPOINT }}?type=with-vpn-1
        ping ya.ru
          
    - name: Detach WireGuard connection
      if: ${{ failure() }}
      shell: bash
      run: |
        echo "${{ env.DateTime }} - Failure" >> ${{ env.LogFile }}
        sudo wg-quick down /etc/wireguard/wg0.conf >> ${{ env.LogFile }}
        echo "${{ env.DateTime }} - Logs from VPN End." >> ${{ env.LogFile }}

    - name: Upload Logs on Failure
      uses: actions/upload-artifact@v4
      with:
        name: Build failure logs
        path: ${{ env.LogDir }}

